Команды: &commands
    Команды:
        Параметры:
            ОтправлятьСообщенияВТелеграм: true
            Приветствие: "Закрываю конфигуратор #ИмяБазы через #Пауза" 
            Окончание: "Конфигуратор базы #ИмяБазы закрыт"  
            ТекстВопроса: "Закрыть конфигуратор базы #ИмяБазы?"          
            Пауза: 300            
        Команды:
            - ЗадатьВопрос
            - ПоказатьПриветствие
            - УстановитьПаузу
            - ОтключитьКонфигураторОтИнформационнойБазы   
            - ПоказатьЗавершение       
BASE1:    
    <<: *commands                    
BASE2:    
    <<: *commands       
