Общие:
    Идентификатор: "Проект"
    Ответственный: "Фамилия Имя"
    КаталогНастроек: settings
    ПутьККаталогуCF: "\\cf"    
    Файлы:
        repo_test: repo_connect_test.xml
        merge: merge.xml  
        metadata: metadata.txt  
        metadata_merge: metadata_merge.xml     
    Телеграм:
        BotID: ""
        Токен: ""
    Debug:
        ИдентификаторБазы: ""
        ИдентификаторКоманд: ""
        КаталогСкрипта: "sync_repo"       
Платформа:
    1cv8: "C:\\Program Files\\1Cv8\\8.3.20.1838\\bin\\1cv8.exe"
    Версия: "8.3.20.1838"
    RAS:
        Сервер: ""
        Порт: ""
    Обновление:
        Сообщение: "Идет обновление"
        КодДоступа: "321"
REPO:    
    Сервер: ""
    Порт: ""
    ИмяБазы: ""
    Конфигуратор:
        Логин: ""
        Пароль: ""
    Хранилище:
        Путь: ""
        Логин: ""
        Пароль: ""    
BASE1:    
    Сервер: ""
    Порт: ""
    ИмяБазы: ""
    Конфигуратор:
        Логин: ""
        Пароль: ""
    Хранилище:
        Путь: ""
        Логин: ""
        Пароль: ""    
BASE1:    
    Сервер: ""
    Порт: ""
    ИмяБазы: ""
    Конфигуратор:
        Логин: ""
        Пароль: ""
    Хранилище:
        Путь: ""
        Логин: ""
        Пароль: ""